# landscape short name
landscapeName: dronecode
# Update with your membership structure
landscapeMemberClasses:
   - name: Platinum Membership
     category: Platinum
   - name: Gold Membership
     category: Gold
   - name: Silver Membership
     category: Silver
# SF Project record ID for your project
project: a0941000002wBzCAAU # Dronecode
# Name of category for members 
landscapeMemberCategory: Dronecode Member
